// Importing the 'moment' library
const moment = require('moment');

// Importing the 'Schema' and 'Types' objects from the 'mongoose' library
const { Schema, Types } = require('mongoose');

// Defining a new Mongoose schema for a 'reaction'
const reactionSchema = new Schema(
    {
     // Defining a unique ID for the reaction, generated by the MongoDB ObjectId function 
        reactionId: {
        type: Schema.Types.ObjectId,
        default: () => new Types.ObjectId(),
      },
      // Defining the body of the reaction, which is a string of up to 280 characters and is required  
      reactionBody: {
        type: String,
        required: true,
        maxlength: 280,
      },
       // Defining the username of the user who made the reaction, which is a required string 
      username: {
        type: String,
        required: true,
      },
       // Defining the creation time of the reaction, which is a Date object with a default value of the current time,
       // formatted using the 'moment' library to display in a more human-readable format 
      createdAt: {
        type: Date,
        default: Date.now,
        get: (timestamp) => moment(timestamp).format('MMM Do, YYYY [at] hh:mm a'),
      },
    },
    {
     // Specifying that any getters defined on the schema should be included when converting the schema to a JSON object   
      toJSON: {
        getters: true,
      },
      id: false,
    }
  );
  // Exporting the 'reactionSchema' object to be used in other parts of the application
  module.exports = reactionSchema;
